version: '3.8'

networks:
  shoes-network:
    driver: bridge
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - shoes-network
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
      - "5005:5005"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
      - "5006:5005"
    depends_on:
      - discovery-server

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
      - "5007:5005"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  order-service:
    build: ./order-service
    ports:
      - "5008:5005"
      - "8083:8083"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  identity-service:
    build: ./identity-service
    ports:
      - "5009:5005"
      - "8081:8081"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cart-service:
    build: ./cart-service
    ports:
      - "5010:5005"
      - "8084:8083"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  promotion-service:
    build: ./promotion-service
    ports:
      - "5011:5005"
      - "8085:8082"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    extra_hosts:
      - "host.docker.internal:host-gateway"
