spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/order-service?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      initialization-fail-timeout: 60000

  kafka:
    bootstrap-servers: kafka:29092 # Gọi tới tên container Kafka trong mạng Docker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: shoes-microservices-super-secret-jwt-key-min-256-bits-for-hs256-algorithm-pls-change-in-prod
    expiration-ms: 86400000
security:
  strategy: MODE_INHERITABLETHREADLOCAL