spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/identity_db?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    open-in-view: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: shoes-microservices-super-secret-jwt-key-min-256-bits-for-hs256-algorithm-pls-change-in-prod
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
