spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://mysql:3306/cart_db?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Feign client default config
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
